// Exercise library — rebuilt from fitness_exercise_muscle_audit_v2.xlsx
// Muscle taxonomy: 20 specific groups across Upper Body / Core / Lower Body / Other
// clickableSelections → which muscle filter buttons surface this exercise
// anatomicalHighlight → all muscles lit on the body diagram

export type MuscleGroup =
  | "Chest" | "Lats" | "Upper Back" | "Traps" | "Shoulders"
  | "Biceps" | "Triceps" | "Forearms" | "Neck"
  | "Abs" | "Obliques" | "Lower Back"
  | "Glutes" | "Quads" | "Hamstrings" | "Calves" | "Adductors" | "Abductors"
  | "Cardio" | "Full Body";

export type AppSection = "Upper Body" | "Core" | "Lower Body" | "Multiple" | "Other";

export type ExerciseType =
  | "barbell" | "dumbbell" | "cable" | "bodyweight" | "machine"
  | "skill" | "cardio" | "kettlebell" | "full body";

export interface ExerciseDef {
  name: string;
  appSection: AppSection;
  /** Muscle group filter buttons this exercise appears under */
  clickableSelections: MuscleGroup[];
  primaryMuscles: MuscleGroup[];
  secondaryMuscles: MuscleGroup[];
  /** All muscles to highlight on the anatomical figure */
  anatomicalHighlight: MuscleGroup[];
  type: ExerciseType;
  isHold: boolean;
}

export const EXERCISE_LIBRARY: ExerciseDef[] = [
  // ── UPPER BODY ─────────────────────────────────────────────────────────────
  { name: "Adv Tuck Planche",        appSection: "Upper Body",  clickableSelections: ["Shoulders","Chest","Triceps"],          primaryMuscles: ["Shoulders","Chest","Triceps"],               secondaryMuscles: ["Abs"],                                                 anatomicalHighlight: ["Shoulders","Chest","Triceps","Abs"],                           type: "skill",      isHold: true  },
  { name: "Australian Pull-Up",       appSection: "Upper Body",  clickableSelections: ["Upper Back","Lats"],                    primaryMuscles: ["Upper Back","Lats"],                         secondaryMuscles: ["Biceps","Forearms"],                                    anatomicalHighlight: ["Upper Back","Lats","Biceps","Forearms"],                       type: "bodyweight", isHold: false },
  { name: "Back Lever",               appSection: "Upper Body",  clickableSelections: ["Shoulders","Lats"],                     primaryMuscles: ["Shoulders","Lats"],                          secondaryMuscles: ["Chest","Abs"],                                         anatomicalHighlight: ["Shoulders","Lats","Chest","Abs"],                              type: "skill",      isHold: true  },
  { name: "Barbell Curl",             appSection: "Upper Body",  clickableSelections: ["Biceps"],                               primaryMuscles: ["Biceps"],                                   secondaryMuscles: ["Forearms"],                                            anatomicalHighlight: ["Biceps","Forearms"],                                           type: "barbell",    isHold: false },
  { name: "Barbell Row",              appSection: "Upper Body",  clickableSelections: ["Upper Back","Lats"],                    primaryMuscles: ["Upper Back","Lats"],                         secondaryMuscles: ["Biceps","Forearms","Lower Back"],                       anatomicalHighlight: ["Upper Back","Lats","Biceps","Forearms","Lower Back"],          type: "barbell",    isHold: false },
  { name: "Bench Press",              appSection: "Upper Body",  clickableSelections: ["Chest"],                                primaryMuscles: ["Chest"],                                    secondaryMuscles: ["Triceps","Shoulders"],                                  anatomicalHighlight: ["Chest","Triceps","Shoulders"],                                 type: "barbell",    isHold: false },
  { name: "Cable Fly",                appSection: "Upper Body",  clickableSelections: ["Chest"],                                primaryMuscles: ["Chest"],                                    secondaryMuscles: ["Triceps","Shoulders"],                                  anatomicalHighlight: ["Chest","Triceps","Shoulders"],                                 type: "cable",      isHold: false },
  { name: "Chest Press Machine",      appSection: "Upper Body",  clickableSelections: ["Chest"],                                primaryMuscles: ["Chest"],                                    secondaryMuscles: ["Triceps","Shoulders"],                                  anatomicalHighlight: ["Chest","Triceps","Shoulders"],                                 type: "machine",    isHold: false },
  { name: "Chin-Up",                  appSection: "Upper Body",  clickableSelections: ["Lats","Biceps"],                        primaryMuscles: ["Lats","Biceps"],                             secondaryMuscles: ["Upper Back","Forearms"],                                anatomicalHighlight: ["Lats","Biceps","Upper Back","Forearms"],                       type: "bodyweight", isHold: false },
  { name: "Close-Grip Bench",         appSection: "Upper Body",  clickableSelections: ["Triceps","Chest"],                      primaryMuscles: ["Triceps","Chest"],                           secondaryMuscles: ["Shoulders"],                                           anatomicalHighlight: ["Triceps","Chest","Shoulders"],                                 type: "barbell",    isHold: false },
  { name: "Concentration Curl",       appSection: "Upper Body",  clickableSelections: ["Biceps"],                               primaryMuscles: ["Biceps"],                                   secondaryMuscles: ["Forearms"],                                            anatomicalHighlight: ["Biceps","Forearms"],                                           type: "dumbbell",   isHold: false },
  { name: "Dead Hang",                appSection: "Upper Body",  clickableSelections: ["Forearms"],                             primaryMuscles: ["Forearms"],                                 secondaryMuscles: ["Lats","Shoulders"],                                    anatomicalHighlight: ["Forearms","Lats","Shoulders"],                                 type: "skill",      isHold: true  },
  { name: "Diamond Push-Up",          appSection: "Upper Body",  clickableSelections: ["Triceps","Chest"],                      primaryMuscles: ["Triceps","Chest"],                           secondaryMuscles: ["Shoulders","Abs"],                                     anatomicalHighlight: ["Triceps","Chest","Shoulders","Abs"],                           type: "bodyweight", isHold: false },
  { name: "Dips",                     appSection: "Upper Body",  clickableSelections: ["Chest","Triceps"],                      primaryMuscles: ["Chest","Triceps"],                           secondaryMuscles: ["Shoulders"],                                           anatomicalHighlight: ["Chest","Triceps","Shoulders"],                                 type: "bodyweight", isHold: false },
  { name: "Dumbbell Fly",             appSection: "Upper Body",  clickableSelections: ["Chest"],                                primaryMuscles: ["Chest"],                                    secondaryMuscles: ["Triceps","Shoulders"],                                  anatomicalHighlight: ["Chest","Triceps","Shoulders"],                                 type: "dumbbell",   isHold: false },
  { name: "Dumbbell Row",             appSection: "Upper Body",  clickableSelections: ["Lats","Upper Back"],                    primaryMuscles: ["Lats","Upper Back"],                         secondaryMuscles: ["Biceps","Forearms"],                                    anatomicalHighlight: ["Lats","Upper Back","Biceps","Forearms"],                       type: "dumbbell",   isHold: false },
  { name: "Dumbbell Shoulder Press",  appSection: "Upper Body",  clickableSelections: ["Shoulders"],                            primaryMuscles: ["Shoulders"],                                secondaryMuscles: ["Triceps","Traps"],                                     anatomicalHighlight: ["Shoulders","Triceps","Traps"],                                 type: "dumbbell",   isHold: false },
  { name: "EZ Bar Curl",              appSection: "Upper Body",  clickableSelections: ["Biceps"],                               primaryMuscles: ["Biceps"],                                   secondaryMuscles: ["Forearms"],                                            anatomicalHighlight: ["Biceps","Forearms"],                                           type: "barbell",    isHold: false },
  { name: "Face Pulls",               appSection: "Upper Body",  clickableSelections: ["Upper Back","Shoulders"],               primaryMuscles: ["Upper Back","Shoulders"],                    secondaryMuscles: ["Traps"],                                               anatomicalHighlight: ["Upper Back","Shoulders","Traps"],                              type: "cable",      isHold: false },
  { name: "Front Raise",              appSection: "Upper Body",  clickableSelections: ["Shoulders"],                            primaryMuscles: ["Shoulders"],                                secondaryMuscles: ["Chest"],                                               anatomicalHighlight: ["Shoulders","Chest"],                                           type: "dumbbell",   isHold: false },
  { name: "Hammer Curl",              appSection: "Upper Body",  clickableSelections: ["Biceps","Forearms"],                    primaryMuscles: ["Biceps","Forearms"],                         secondaryMuscles: [],                                                      anatomicalHighlight: ["Biceps","Forearms"],                                           type: "dumbbell",   isHold: false },
  { name: "Handstand Push-Up",        appSection: "Upper Body",  clickableSelections: ["Shoulders"],                            primaryMuscles: ["Shoulders"],                                secondaryMuscles: ["Triceps","Traps"],                                     anatomicalHighlight: ["Shoulders","Triceps","Traps"],                                 type: "skill",      isHold: false },
  { name: "Handstand Walk",           appSection: "Upper Body",  clickableSelections: ["Shoulders"],                            primaryMuscles: ["Shoulders"],                                secondaryMuscles: ["Triceps","Abs","Forearms"],                             anatomicalHighlight: ["Shoulders","Triceps","Abs","Forearms"],                        type: "skill",      isHold: false },
  { name: "Incline Bench Press",      appSection: "Upper Body",  clickableSelections: ["Chest"],                                primaryMuscles: ["Chest"],                                    secondaryMuscles: ["Shoulders","Triceps"],                                  anatomicalHighlight: ["Chest","Shoulders","Triceps"],                                 type: "barbell",    isHold: false },
  { name: "Incline Curl",             appSection: "Upper Body",  clickableSelections: ["Biceps"],                               primaryMuscles: ["Biceps"],                                   secondaryMuscles: ["Forearms"],                                            anatomicalHighlight: ["Biceps","Forearms"],                                           type: "dumbbell",   isHold: false },
  { name: "Incline Push-Up",          appSection: "Upper Body",  clickableSelections: ["Chest"],                                primaryMuscles: ["Chest"],                                    secondaryMuscles: ["Triceps","Shoulders","Abs"],                            anatomicalHighlight: ["Chest","Triceps","Shoulders","Abs"],                           type: "bodyweight", isHold: false },
  { name: "Iron Cross",               appSection: "Upper Body",  clickableSelections: ["Shoulders","Chest"],                    primaryMuscles: ["Shoulders","Chest"],                         secondaryMuscles: ["Lats","Biceps"],                                       anatomicalHighlight: ["Shoulders","Chest","Lats","Biceps"],                           type: "skill",      isHold: true  },
  { name: "Lat Pulldown",             appSection: "Upper Body",  clickableSelections: ["Lats"],                                 primaryMuscles: ["Lats"],                                     secondaryMuscles: ["Biceps","Upper Back","Forearms"],                       anatomicalHighlight: ["Lats","Biceps","Upper Back","Forearms"],                       type: "machine",    isHold: false },
  { name: "Lateral Raise",            appSection: "Upper Body",  clickableSelections: ["Shoulders"],                            primaryMuscles: ["Shoulders"],                                secondaryMuscles: ["Traps"],                                               anatomicalHighlight: ["Shoulders","Traps"],                                           type: "dumbbell",   isHold: false },
  { name: "Machine Bicep Curl",       appSection: "Upper Body",  clickableSelections: ["Biceps"],                               primaryMuscles: ["Biceps"],                                   secondaryMuscles: ["Forearms"],                                            anatomicalHighlight: ["Biceps","Forearms"],                                           type: "machine",    isHold: false },
  { name: "Overhead Press",           appSection: "Upper Body",  clickableSelections: ["Shoulders"],                            primaryMuscles: ["Shoulders"],                                secondaryMuscles: ["Triceps","Traps"],                                     anatomicalHighlight: ["Shoulders","Triceps","Traps"],                                 type: "barbell",    isHold: false },
  { name: "Overhead Tricep Ext",      appSection: "Upper Body",  clickableSelections: ["Triceps"],                              primaryMuscles: ["Triceps"],                                  secondaryMuscles: [],                                                      anatomicalHighlight: ["Triceps"],                                                     type: "dumbbell",   isHold: false },
  { name: "Pike Push-Up",             appSection: "Upper Body",  clickableSelections: ["Shoulders"],                            primaryMuscles: ["Shoulders"],                                secondaryMuscles: ["Triceps","Chest"],                                     anatomicalHighlight: ["Shoulders","Triceps","Chest"],                                 type: "bodyweight", isHold: false },
  { name: "Planche Lean",             appSection: "Upper Body",  clickableSelections: ["Shoulders","Chest"],                    primaryMuscles: ["Shoulders","Chest"],                         secondaryMuscles: ["Triceps","Abs"],                                       anatomicalHighlight: ["Shoulders","Chest","Triceps","Abs"],                           type: "skill",      isHold: true  },
  { name: "Preacher Curl",            appSection: "Upper Body",  clickableSelections: ["Biceps"],                               primaryMuscles: ["Biceps"],                                   secondaryMuscles: ["Forearms"],                                            anatomicalHighlight: ["Biceps","Forearms"],                                           type: "machine",    isHold: false },
  { name: "Pull-Up",                  appSection: "Upper Body",  clickableSelections: ["Lats"],                                 primaryMuscles: ["Lats"],                                     secondaryMuscles: ["Biceps","Upper Back","Forearms"],                       anatomicalHighlight: ["Lats","Biceps","Upper Back","Forearms"],                       type: "bodyweight", isHold: false },
  { name: "Push-Up",                  appSection: "Upper Body",  clickableSelections: ["Chest"],                                primaryMuscles: ["Chest"],                                    secondaryMuscles: ["Triceps","Shoulders","Abs"],                            anatomicalHighlight: ["Chest","Triceps","Shoulders","Abs"],                           type: "bodyweight", isHold: false },
  { name: "Ring Support Hold",        appSection: "Upper Body",  clickableSelections: ["Triceps","Shoulders"],                  primaryMuscles: ["Triceps","Shoulders"],                       secondaryMuscles: ["Chest","Abs"],                                         anatomicalHighlight: ["Triceps","Shoulders","Chest","Abs"],                           type: "skill",      isHold: true  },
  { name: "Seated Cable Row",         appSection: "Upper Body",  clickableSelections: ["Upper Back","Lats"],                    primaryMuscles: ["Upper Back","Lats"],                         secondaryMuscles: ["Biceps","Forearms"],                                    anatomicalHighlight: ["Upper Back","Lats","Biceps","Forearms"],                       type: "cable",      isHold: false },
  { name: "Skull Crusher",            appSection: "Upper Body",  clickableSelections: ["Triceps"],                              primaryMuscles: ["Triceps"],                                  secondaryMuscles: [],                                                      anatomicalHighlight: ["Triceps"],                                                     type: "barbell",    isHold: false },
  { name: "Tricep Pushdown",          appSection: "Upper Body",  clickableSelections: ["Triceps"],                              primaryMuscles: ["Triceps"],                                  secondaryMuscles: [],                                                      anatomicalHighlight: ["Triceps"],                                                     type: "cable",      isHold: false },
  { name: "Tuck Planche",             appSection: "Upper Body",  clickableSelections: ["Shoulders","Chest","Triceps"],          primaryMuscles: ["Shoulders","Chest","Triceps"],               secondaryMuscles: ["Abs"],                                                 anatomicalHighlight: ["Shoulders","Chest","Triceps","Abs"],                           type: "skill",      isHold: true  },
  { name: "Upright Row",              appSection: "Upper Body",  clickableSelections: ["Shoulders","Traps"],                    primaryMuscles: ["Shoulders","Traps"],                         secondaryMuscles: ["Biceps"],                                              anatomicalHighlight: ["Shoulders","Traps","Biceps"],                                  type: "barbell",    isHold: false },
  { name: "Wide Grip Pull-Up",        appSection: "Upper Body",  clickableSelections: ["Lats"],                                 primaryMuscles: ["Lats"],                                     secondaryMuscles: ["Upper Back","Biceps","Forearms"],                       anatomicalHighlight: ["Lats","Upper Back","Biceps","Forearms"],                       type: "bodyweight", isHold: false },

  // ── CORE ───────────────────────────────────────────────────────────────────
  { name: "Ab Rollout",               appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: ["Lats","Shoulders"],                                    anatomicalHighlight: ["Abs","Lats","Shoulders"],                                      type: "bodyweight", isHold: false },
  { name: "Arch Body Hold",           appSection: "Core",        clickableSelections: ["Lower Back"],                           primaryMuscles: ["Lower Back"],                               secondaryMuscles: ["Glutes","Hamstrings","Upper Back"],                     anatomicalHighlight: ["Lower Back","Glutes","Hamstrings","Upper Back"],               type: "skill",      isHold: true  },
  { name: "Dead Bug",                 appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: ["Obliques"],                                            anatomicalHighlight: ["Abs","Obliques"],                                              type: "bodyweight", isHold: false },
  { name: "Dragon Flag",              appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: ["Lats"],                                                anatomicalHighlight: ["Abs","Lats"],                                                  type: "skill",      isHold: false },
  { name: "Hanging Leg Raises",       appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: ["Forearms"],                                            anatomicalHighlight: ["Abs","Forearms"],                                              type: "bodyweight", isHold: false },
  { name: "Hollow Body Hold",         appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: [],                                                      anatomicalHighlight: ["Abs"],                                                         type: "skill",      isHold: true  },
  { name: "L-Sit",                    appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: ["Triceps","Shoulders","Quads"],                          anatomicalHighlight: ["Abs","Triceps","Shoulders","Quads"],                           type: "skill",      isHold: true  },
  { name: "Plank",                    appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: ["Obliques","Shoulders"],                                 anatomicalHighlight: ["Abs","Obliques","Shoulders"],                                  type: "skill",      isHold: true  },
  { name: "Toes to Bar",              appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: ["Lats","Forearms"],                                     anatomicalHighlight: ["Abs","Lats","Forearms"],                                       type: "bodyweight", isHold: false },
  { name: "V-Sit",                    appSection: "Core",        clickableSelections: ["Abs"],                                  primaryMuscles: ["Abs"],                                      secondaryMuscles: ["Quads","Shoulders"],                                    anatomicalHighlight: ["Abs","Quads","Shoulders"],                                     type: "skill",      isHold: true  },

  // ── LOWER BODY ─────────────────────────────────────────────────────────────
  { name: "Box Jumps",                appSection: "Lower Body",  clickableSelections: ["Quads","Glutes"],                       primaryMuscles: ["Quads","Glutes"],                            secondaryMuscles: ["Hamstrings","Calves"],                                  anatomicalHighlight: ["Quads","Glutes","Hamstrings","Calves"],                        type: "bodyweight", isHold: false },
  { name: "Bulgarian Split Squat",    appSection: "Lower Body",  clickableSelections: ["Quads","Glutes"],                       primaryMuscles: ["Quads","Glutes"],                            secondaryMuscles: ["Hamstrings","Adductors"],                               anatomicalHighlight: ["Quads","Glutes","Hamstrings","Adductors"],                     type: "bodyweight", isHold: false },
  { name: "Calf Raise",               appSection: "Lower Body",  clickableSelections: ["Calves"],                               primaryMuscles: ["Calves"],                                   secondaryMuscles: [],                                                      anatomicalHighlight: ["Calves"],                                                      type: "bodyweight", isHold: false },
  { name: "Hamstring Curl Machine",   appSection: "Lower Body",  clickableSelections: ["Hamstrings"],                           primaryMuscles: ["Hamstrings"],                               secondaryMuscles: [],                                                      anatomicalHighlight: ["Hamstrings"],                                                  type: "machine",    isHold: false },
  { name: "Hip Abduction",            appSection: "Lower Body",  clickableSelections: ["Abductors","Glutes"],                   primaryMuscles: ["Abductors","Glutes"],                        secondaryMuscles: [],                                                      anatomicalHighlight: ["Abductors","Glutes"],                                          type: "machine",    isHold: false },
  { name: "Hip Thrust",               appSection: "Lower Body",  clickableSelections: ["Glutes"],                               primaryMuscles: ["Glutes"],                                   secondaryMuscles: ["Hamstrings","Adductors"],                               anatomicalHighlight: ["Glutes","Hamstrings","Adductors"],                             type: "barbell",    isHold: false },
  { name: "Leg Extension",            appSection: "Lower Body",  clickableSelections: ["Quads"],                                primaryMuscles: ["Quads"],                                    secondaryMuscles: [],                                                      anatomicalHighlight: ["Quads"],                                                       type: "machine",    isHold: false },
  { name: "Leg Press",                appSection: "Lower Body",  clickableSelections: ["Quads","Glutes"],                       primaryMuscles: ["Quads","Glutes"],                            secondaryMuscles: ["Hamstrings","Adductors"],                               anatomicalHighlight: ["Quads","Glutes","Hamstrings","Adductors"],                     type: "machine",    isHold: false },
  { name: "Nordic Curl",              appSection: "Lower Body",  clickableSelections: ["Hamstrings"],                           primaryMuscles: ["Hamstrings"],                               secondaryMuscles: ["Glutes","Calves"],                                     anatomicalHighlight: ["Hamstrings","Glutes","Calves"],                                type: "bodyweight", isHold: false },
  { name: "Pistol Squat",             appSection: "Lower Body",  clickableSelections: ["Quads","Glutes"],                       primaryMuscles: ["Quads","Glutes"],                            secondaryMuscles: ["Hamstrings","Adductors","Calves","Abs"],                anatomicalHighlight: ["Quads","Glutes","Hamstrings","Adductors","Calves","Abs"],      type: "skill",      isHold: false },
  { name: "Romanian Deadlift",        appSection: "Lower Body",  clickableSelections: ["Hamstrings","Glutes"],                  primaryMuscles: ["Hamstrings","Glutes"],                       secondaryMuscles: ["Lower Back","Forearms"],                                anatomicalHighlight: ["Hamstrings","Glutes","Lower Back","Forearms"],                 type: "barbell",    isHold: false },
  { name: "Squat",                    appSection: "Lower Body",  clickableSelections: ["Quads","Glutes"],                       primaryMuscles: ["Quads","Glutes"],                            secondaryMuscles: ["Adductors","Hamstrings","Abs"],                         anatomicalHighlight: ["Quads","Glutes","Adductors","Hamstrings","Abs"],               type: "barbell",    isHold: false },
  { name: "Walking Lunge",            appSection: "Lower Body",  clickableSelections: ["Quads","Glutes"],                       primaryMuscles: ["Quads","Glutes"],                            secondaryMuscles: ["Hamstrings","Adductors","Calves"],                      anatomicalHighlight: ["Quads","Glutes","Hamstrings","Adductors","Calves"],            type: "bodyweight", isHold: false },
  { name: "Wall Sit",                 appSection: "Lower Body",  clickableSelections: ["Quads"],                                primaryMuscles: ["Quads"],                                    secondaryMuscles: ["Glutes","Calves"],                                     anatomicalHighlight: ["Quads","Glutes","Calves"],                                     type: "skill",      isHold: true  },

  // ── MULTIPLE ────────────────────────────────────────────────────────────────
  { name: "Deadlift",                 appSection: "Multiple",    clickableSelections: ["Hamstrings","Glutes","Lower Back"],      primaryMuscles: ["Hamstrings","Glutes","Lower Back"],          secondaryMuscles: ["Quads","Upper Back","Traps","Forearms","Adductors"],    anatomicalHighlight: ["Hamstrings","Glutes","Lower Back","Quads","Upper Back","Traps","Forearms","Adductors"], type: "barbell", isHold: false },
  { name: "Front Lever",              appSection: "Multiple",    clickableSelections: ["Lats","Abs"],                           primaryMuscles: ["Lats","Abs"],                               secondaryMuscles: ["Shoulders","Upper Back"],                               anatomicalHighlight: ["Lats","Abs","Shoulders","Upper Back"],                         type: "skill",      isHold: true  },
  { name: "Human Flag",               appSection: "Multiple",    clickableSelections: ["Obliques","Lats"],                      primaryMuscles: ["Obliques","Lats"],                           secondaryMuscles: ["Shoulders","Abs","Forearms"],                           anatomicalHighlight: ["Obliques","Lats","Shoulders","Abs","Forearms"],                type: "skill",      isHold: true  },

  // ── CARDIO ─────────────────────────────────────────────────────────────────
  { name: "Assault Bike",             appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Quads","Hamstrings","Glutes","Shoulders","Triceps"],    anatomicalHighlight: ["Quads","Hamstrings","Glutes","Shoulders","Triceps"],           type: "cardio",     isHold: false },
  { name: "Battle Ropes",             appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Shoulders","Forearms","Abs"],                           anatomicalHighlight: ["Shoulders","Forearms","Abs"],                                  type: "cardio",     isHold: false },
  { name: "Cycling",                  appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Hamstrings","Calves"],                 anatomicalHighlight: ["Quads","Glutes","Hamstrings","Calves"],                        type: "cardio",     isHold: false },
  { name: "Jump Rope",                appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Calves","Shoulders","Forearms"],                        anatomicalHighlight: ["Calves","Shoulders","Forearms"],                               type: "cardio",     isHold: false },
  { name: "Row Machine",              appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Lats","Upper Back","Quads","Glutes","Biceps"],          anatomicalHighlight: ["Lats","Upper Back","Quads","Glutes","Biceps"],                 type: "cardio",     isHold: false },
  { name: "Running",                  appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Quads","Hamstrings","Glutes","Calves"],                 anatomicalHighlight: ["Quads","Hamstrings","Glutes","Calves"],                        type: "cardio",     isHold: false },
  { name: "Spinning / Bicycle Sprints", appSection: "Other",     clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Hamstrings","Calves"],                 anatomicalHighlight: ["Quads","Glutes","Hamstrings","Calves"],                        type: "cardio",     isHold: false },
  { name: "Sprints",                  appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Calves"],                 anatomicalHighlight: ["Glutes","Hamstrings","Quads","Calves"],                        type: "cardio",     isHold: false },
  { name: "Stair Climber",            appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Quads","Hamstrings","Calves"],                 anatomicalHighlight: ["Glutes","Quads","Hamstrings","Calves"],                        type: "cardio",     isHold: false },
  { name: "Stair Machine Floors",     appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Quads","Hamstrings","Calves"],                 anatomicalHighlight: ["Glutes","Quads","Hamstrings","Calves"],                        type: "cardio",     isHold: false },
  { name: "Stair Machine Steps",      appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Quads","Hamstrings","Calves"],                 anatomicalHighlight: ["Glutes","Quads","Hamstrings","Calves"],                        type: "cardio",     isHold: false },
  { name: "Stationary Bike",          appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Hamstrings","Calves"],                 anatomicalHighlight: ["Quads","Glutes","Hamstrings","Calves"],                        type: "cardio",     isHold: false },
  { name: "Swimming",                 appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Lats","Shoulders","Chest","Triceps","Abs"],             anatomicalHighlight: ["Lats","Shoulders","Chest","Triceps","Abs"],                    type: "cardio",     isHold: false },
  { name: "Treadmill Run",            appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Quads","Hamstrings","Glutes","Calves"],                 anatomicalHighlight: ["Quads","Hamstrings","Glutes","Calves"],                        type: "cardio",     isHold: false },
  { name: "Walking",                  appSection: "Other",       clickableSelections: ["Cardio"],                               primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Quads","Hamstrings","Calves"],                 anatomicalHighlight: ["Glutes","Quads","Hamstrings","Calves"],                        type: "cardio",     isHold: false },

  // ── FULL BODY ──────────────────────────────────────────────────────────────
  { name: "Ball Slams",               appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Shoulders","Lats","Abs","Glutes","Quads"],              anatomicalHighlight: ["Shoulders","Lats","Abs","Glutes","Quads"],                     type: "full body",  isHold: false },
  { name: "Barbell Thruster",         appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Shoulders","Triceps"],                 anatomicalHighlight: ["Quads","Glutes","Shoulders","Triceps"],                        type: "full body",  isHold: false },
  { name: "Bear Crawl",               appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Shoulders","Abs","Quads","Glutes"],                     anatomicalHighlight: ["Shoulders","Abs","Quads","Glutes"],                            type: "full body",  isHold: false },
  { name: "Burpee",                   appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Chest","Shoulders","Triceps","Quads","Glutes","Abs"],   anatomicalHighlight: ["Chest","Shoulders","Triceps","Quads","Glutes","Abs"],          type: "full body",  isHold: false },
  { name: "Burpee Broad Jumps",       appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Hamstrings","Chest","Shoulders","Triceps"], anatomicalHighlight: ["Quads","Glutes","Hamstrings","Chest","Shoulders","Triceps"], type: "full body",  isHold: false },
  { name: "Burpee Over Bar",          appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Chest","Shoulders","Triceps","Quads","Glutes"],         anatomicalHighlight: ["Chest","Shoulders","Triceps","Quads","Glutes"],                type: "full body",  isHold: false },
  { name: "Clean",                    appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Traps","Shoulders"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Traps","Shoulders"],             type: "full body",  isHold: false },
  { name: "Clean and Jerk",           appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Hamstrings","Shoulders","Triceps","Traps"], anatomicalHighlight: ["Quads","Glutes","Hamstrings","Shoulders","Triceps","Traps"], type: "full body",  isHold: false },
  { name: "Clean and Press",          appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Hamstrings","Shoulders","Triceps"],    anatomicalHighlight: ["Quads","Glutes","Hamstrings","Shoulders","Triceps"],           type: "full body",  isHold: false },
  { name: "Clean Pull",               appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Traps"],                  anatomicalHighlight: ["Glutes","Hamstrings","Quads","Traps"],                         type: "full body",  isHold: false },
  { name: "Deadlift High Pull",       appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Traps","Shoulders"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Traps","Shoulders"],             type: "full body",  isHold: false },
  { name: "Downward Dog",             appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Shoulders","Hamstrings","Calves"],                      anatomicalHighlight: ["Shoulders","Hamstrings","Calves"],                             type: "full body",  isHold: false },
  { name: "Dumbbell Snatch",          appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],             type: "full body",  isHold: false },
  { name: "Farmer's Walk",            appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Forearms","Traps","Abs","Glutes","Calves"],             anatomicalHighlight: ["Forearms","Traps","Abs","Glutes","Calves"],                    type: "full body",  isHold: false },
  { name: "Front Lever Hold",         appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Lats","Abs","Shoulders","Upper Back"],                  anatomicalHighlight: ["Lats","Abs","Shoulders","Upper Back"],                         type: "full body",  isHold: true  },
  { name: "Front Lever Raise",        appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Lats","Abs","Shoulders","Upper Back"],                  anatomicalHighlight: ["Lats","Abs","Shoulders","Upper Back"],                         type: "full body",  isHold: false },
  { name: "Handstand Hold",           appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: ["Shoulders"],                                secondaryMuscles: ["Triceps","Abs","Traps"],                                anatomicalHighlight: ["Shoulders","Triceps","Abs","Traps"],                           type: "skill",      isHold: true  },
  { name: "Hang Clean",               appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Traps","Shoulders"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Traps","Shoulders"],             type: "full body",  isHold: false },
  { name: "Hang Snatch",              appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],             type: "full body",  isHold: false },
  { name: "High Knee",                appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Calves","Abs"],                        anatomicalHighlight: ["Quads","Glutes","Calves","Abs"],                               type: "full body",  isHold: false },
  { name: "High Knee Skips",          appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Calves","Abs"],                        anatomicalHighlight: ["Quads","Glutes","Calves","Abs"],                               type: "full body",  isHold: false },
  { name: "Jump Shrug",               appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Traps","Calves"],         anatomicalHighlight: ["Glutes","Hamstrings","Quads","Traps","Calves"],                type: "full body",  isHold: false },
  { name: "Jumping Jack",             appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Calves","Shoulders","Glutes"],                          anatomicalHighlight: ["Calves","Shoulders","Glutes"],                                 type: "full body",  isHold: false },
  { name: "Kettlebell Clean",         appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Traps","Shoulders"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Traps","Shoulders"],             type: "kettlebell", isHold: false },
  { name: "Kettlebell High Pull",     appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Traps","Shoulders"],              anatomicalHighlight: ["Glutes","Hamstrings","Traps","Shoulders"],                     type: "kettlebell", isHold: false },
  { name: "Kettlebell Snatch",        appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],             type: "kettlebell", isHold: false },
  { name: "Kettlebell Swing",         appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Lower Back","Abs"],               anatomicalHighlight: ["Glutes","Hamstrings","Lower Back","Abs"],                      type: "kettlebell", isHold: false },
  { name: "Kettlebell Turkish Get-Up",appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Shoulders","Abs","Glutes","Quads"],                     anatomicalHighlight: ["Shoulders","Abs","Glutes","Quads"],                            type: "kettlebell", isHold: false },
  { name: "Landmine Squat and Press", appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Shoulders","Triceps"],                 anatomicalHighlight: ["Quads","Glutes","Shoulders","Triceps"],                        type: "full body",  isHold: false },
  { name: "Mountain Climber",         appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Abs","Shoulders","Quads"],                              anatomicalHighlight: ["Abs","Shoulders","Quads"],                                     type: "full body",  isHold: false },
  { name: "Muscle Up",                appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Lats","Biceps","Triceps","Chest","Shoulders"],          anatomicalHighlight: ["Lats","Biceps","Triceps","Chest","Shoulders"],                 type: "full body",  isHold: false },
  { name: "Overhead Squat",           appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Shoulders","Upper Back","Abs"],        anatomicalHighlight: ["Quads","Glutes","Shoulders","Upper Back","Abs"],               type: "full body",  isHold: false },
  { name: "Pilates",                  appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: [],                                                      anatomicalHighlight: [],                                                              type: "full body",  isHold: false },
  { name: "Power Clean",              appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: ["Glutes","Hamstrings","Quads","Traps","Shoulders","Forearms","Abs"], secondaryMuscles: [],                          anatomicalHighlight: ["Glutes","Hamstrings","Quads","Traps","Shoulders","Forearms","Abs"], type: "full body", isHold: false },
  { name: "Power Snatch",             appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],             type: "full body",  isHold: false },
  { name: "Press Under",              appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Shoulders","Triceps","Quads","Glutes"],                 anatomicalHighlight: ["Shoulders","Triceps","Quads","Glutes"],                        type: "full body",  isHold: false },
  { name: "Sled Pull",                appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Hamstrings","Calves","Upper Back"],    anatomicalHighlight: ["Quads","Glutes","Hamstrings","Calves","Upper Back"],           type: "full body",  isHold: false },
  { name: "Sled Push",                appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Calves","Shoulders","Triceps"],        anatomicalHighlight: ["Quads","Glutes","Calves","Shoulders","Triceps"],               type: "full body",  isHold: false },
  { name: "Snatch",                   appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],      anatomicalHighlight: ["Glutes","Hamstrings","Quads","Shoulders","Traps"],             type: "full body",  isHold: false },
  { name: "Split Jerk",               appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Shoulders","Triceps","Quads","Glutes"],                 anatomicalHighlight: ["Shoulders","Triceps","Quads","Glutes"],                        type: "full body",  isHold: false },
  { name: "Squat Row",                appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Lats","Upper Back","Biceps"],          anatomicalHighlight: ["Quads","Glutes","Lats","Upper Back","Biceps"],                 type: "full body",  isHold: false },
  { name: "Suitcase Carry Dumbbell",  appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Forearms","Obliques","Traps","Glutes"],                 anatomicalHighlight: ["Forearms","Obliques","Traps","Glutes"],                        type: "full body",  isHold: false },
  { name: "Thruster (Kettlebell)",    appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Shoulders","Triceps"],                 anatomicalHighlight: ["Quads","Glutes","Shoulders","Triceps"],                        type: "kettlebell", isHold: false },
  { name: "Wall Ball",                appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: ["Quads","Glutes","Shoulders","Triceps"],                 anatomicalHighlight: ["Quads","Glutes","Shoulders","Triceps"],                        type: "full body",  isHold: false },
  { name: "Warm-Up",                  appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: [],                                                      anatomicalHighlight: [],                                                              type: "full body",  isHold: false },
  { name: "Yoga",                     appSection: "Other",       clickableSelections: ["Full Body"],                            primaryMuscles: [],                                           secondaryMuscles: [],                                                      anatomicalHighlight: [],                                                              type: "full body",  isHold: false },
];

/** Return exercises that appear under a given clickable muscle group */
export function getExercisesByMuscle(muscle: MuscleGroup): ExerciseDef[] {
  return EXERCISE_LIBRARY.filter(ex => ex.clickableSelections.includes(muscle));
}

/** All unique clickable muscle groups in use */
export const ALL_MUSCLE_GROUPS: MuscleGroup[] = [
  "Chest","Lats","Upper Back","Traps","Shoulders","Biceps","Triceps","Forearms","Neck",
  "Abs","Obliques","Lower Back",
  "Glutes","Quads","Hamstrings","Calves","Adductors","Abductors",
  "Cardio","Full Body",
];

export const MUSCLE_SECTIONS: { title: string; muscles: MuscleGroup[] }[] = [
  { title: "Upper Body", muscles: ["Chest","Lats","Upper Back","Traps","Shoulders","Biceps","Triceps","Forearms","Neck"] },
  { title: "Core",       muscles: ["Abs","Obliques","Lower Back"] },
  { title: "Lower Body", muscles: ["Glutes","Quads","Hamstrings","Calves","Adductors","Abductors"] },
  { title: "Other",      muscles: ["Cardio","Full Body"] },
];
