import Link from "next/link";

export const metadata = { title: "Privacy Policy — Personal OS" };

const LAST_UPDATED = "September 14, 2026";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen w-full bg-[#0f1117] px-4 py-14 text-white/80">
      <div className="mx-auto max-w-2xl">
        <Link
          href="/welcome"
          className="mb-8 inline-block text-[13px] text-white/40 underline underline-offset-2 transition hover:text-white/70"
        >
          ← Back
        </Link>

        <h1 className="mb-1 text-2xl font-bold text-white">Privacy Policy</h1>
        <p className="mb-8 text-[13px] text-white/40">Last updated {LAST_UPDATED}</p>

        <div className="flex flex-col gap-6 text-[14px] leading-relaxed">
          <p className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-[13px] text-white/50">
            This is a template drafted for a small, personally-operated fitness app. It is not a
            substitute for advice from a licensed attorney — have one review it before relying on
            it for a public or commercial launch.
          </p>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">1. What We Collect</h2>
            <p className="mb-2">
              When you create an account and use Personal OS, we collect:
            </p>
            <p className="mb-1">
              <span className="text-white/60">Account info:</span> the email address and password
              you sign up with, or — if you sign in with Google — your name, email, and profile
              picture as provided by Google.
            </p>
            <p className="mb-1">
              <span className="text-white/60">App data:</span> the workout sessions, sets, reps,
              weights, meals, nutrition targets, goals, and mental-health check-ins you enter.
            </p>
            <p>
              <span className="text-white/60">Technical data:</span> standard server logs (IP
              address, browser type, timestamps) generated by normal web traffic.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">2. How We Use It</h2>
            <p>
              Your data is used only to operate the App for you: to display your history and
              progress, calculate suggested reps/weights for progressive overload, and remember
              your goals and preferences. We do not sell your data or share it with advertisers.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">3. Where It&apos;s Stored</h2>
            <p>
              App data and authentication are handled by Supabase (Postgres database, storage,
              and auth). Data is protected by row-level security so that, in production, you can
              only read and write your own records. If you sign in with Google, authentication is
              brokered through Google&apos;s OAuth service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">4. AI-Generated Content</h2>
            <p>
              Exercise illustrations in the App are generated using an AI image model. Generating
              those images does not involve sending your personal data, workout history, or
              account information to the image-generation provider — only generic exercise
              descriptions are used, independent of any specific user.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">5. Cookies</h2>
            <p>
              The App uses essential cookies only: one to keep you signed in (set by Supabase
              Auth) and one to remember that you&apos;ve completed onboarding. Neither is used for
              advertising or cross-site tracking.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">6. Data Retention</h2>
            <p>
              Your data is retained for as long as your account exists. You can request full
              deletion of your account and all associated data at any time; deletion is
              permanent.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">7. Your Rights</h2>
            <p>
              You can request a copy of your data or its deletion at any time by contacting the
              App&apos;s operator directly.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">8. Children</h2>
            <p>
              The App is not directed at children under 13, and we don&apos;t knowingly collect
              data from anyone under 13.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">9. Changes to This Policy</h2>
            <p>
              This Policy may be updated as the App changes. Continued use after an update means
              you accept the revised Policy.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">10. Contact</h2>
            <p>Questions about this Policy, or data requests, can be sent to the App&apos;s operator directly.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
